export const QUARANTINE_REASONS = [
  'DUPLICATE_PAYMENT',
  'MISSING_WALLET_OWNER',
  'INVALID_CURRENCY',
  'INVALID_AMOUNT',
  'MISSING_SOURCE_REFERENCES',
  'INCONSISTENT_STATUS',
  'UNEXPLAINED_BALANCE_DIFFERENCE',
  'UNSUPPORTED_TEACHER_RELATIONSHIP',
  'FIN_BUG_01_FK',
  'BACKUP_ROW',
  'CACHE_ONLY_BALANCE',
  'UNPARSEABLE_RATE',
] as const;

export type QuarantineReason = (typeof QUARANTINE_REASONS)[number];
