export const FOUNDATION_PERMISSIONS = [
  ['iam.user.read', 'Read users'],
  ['iam.user.manage', 'Manage user account status'],
  ['iam.user_role.manage', 'Assign and remove user roles'],
  ['iam.role_permission.manage', 'Grant and revoke role permissions'],
  ['iam.audit.read', 'Read security audit events'],
  ['candidate.read', 'Read candidate master records'],
  ['candidate.create', 'Create candidate master records'],
  ['candidate.update', 'Update candidate master records'],
  ['candidate.status.manage', 'Change candidate account status'],
  ['candidate.education.read', 'Read candidate education records'],
  ['candidate.education.manage', 'Create and update candidate education records'],
  ['candidate.experience.read', 'Read candidate experience records'],
  ['candidate.experience.manage', 'Create and update candidate experience records'],
  ['candidate.skills.read', 'Read candidate skills and skill tags'],
  ['candidate.skills.manage', 'Create and update candidate skills and skill tags'],
  ['candidate.languages.read', 'Read candidate language records'],
  ['candidate.languages.manage', 'Create and update candidate language records'],
  ['candidate.training.read', 'Read candidate profile training records'],
  ['candidate.training.manage', 'Create and update candidate profile training records'],
] as const;
